### ISSUE TITLE
organize under single `health` package

### ISSUE THREAD

**Issue by keturn** [Terasology/Health#71]
The package names currently used in this module make it difficult to distinguish which classes are in this module and which are from engine or elsewhere.

Recommend all packages here descend from a single `org.terasology.health` (or `org.terasology.module.health`?) instead of `org.terasology.logic` & `rendering`.

**Comment by skaldarnar** [comment]
Totally agree! While we're at it, can we sort and organize the events and components in this module as well? :upside_down_face: 

I think putting modules into a dedicated `org.terasology.module` namespace is a good idea to avoid surprising name clashes. although this should already be less likely if the engine has it's dedicated namespace...

**Comment by skaldarnar** [comment]
Following the same pattern as proposed in Terasology/Inventory#37 I suggest the following structure:

```
org.terasology.module.health
├── components
│   ├── BlockDamagedComponent.java
│   ├── DamageResistComponent.java
│   ├── DamageSoundComponent.java
│   ├── HealthComponent.java
│   └── RegenComponent.java
├── events
│   ├── ActivateRegenEvent.java
│   ├── BeforeDamagedEvent.java
│   ├── BeforeRestoreEvent.java
│   ├── ChangeMaxHealthEvent.java
│   ├── DeactivateRegenEvent.java
│   ├── DoDamageEvent.java
│   ├── DoRestoreEvent.java
│   ├── HealthChangedEvent.java
│   ├── MaxHealthChangedEvent.java
│   ├── OnDamagedEvent.java
│   ├── OnFullyHealedEvent.java
│   ├── OnRestoredEvent.java
│   └── RestoreFullHealthEvent.java
├── systems
│   ├── BlockDamageAuthoritySystem.java
│   ├── DamageAuthoritySystem.java
│   ├── HealthAuthoritySystem.java
│   ├── HealthClientSystem.java
│   ├── RegenAuthoritySystem.java
│   └── RestorationAuthoritySystem.java
└── ui
    ├── BlockDamageRenderer.java
    ├── DirectionalDamageOverlay.java
    ├── HealthHud.java
    └── TimingInformation.java
```

**Comment by keturn** [comment]
this is really opening the can of worms, but do you want to change any of those class names while we're at it?

the thing that made me ask is looking at those events and seeing things like
* some events use prefixes like `Do` and `On`, others don't
* FullyHealed / RestoreFullHealth?

**Comment by skaldarnar** [comment]
> do you want to change any of those class names while we're at it?

Yes, I do :ring:  :sweat_smile:
