### ISSUE TITLE
ComponentSystemManager tries to load system that does not exist

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/Health#87]
This is a mystery to me :crystal_ball: According to the logs, the `ComponentSystemManager` is trying to load a `CoreHealthSystem` as a system, but complains that it is not a subclass of `ComponentSystem`. The mystery part - this class does not (no longer) exist, not in this module nor in any other module :eyes: 

Could this be a reflection issue?

```
22:59:45.674 [main] ERROR o.t.e.core.ComponentSystemManager - Cannot load CoreHealthSystem, must be a subclass of ComponentSystem
```

**Comment by keturn** [comment]
Question becomes: what has the reference to the class that doesn't exist?

Save data? Some dependent module compiled against an older version? are there any other data files that reference Systems?

**Comment by skaldarnar** [comment]
Can't reproduce this after a good `gradlew clean` and `git clean` of the workspace. So, whatever had cached this is gone now :shrug:
